### ISSUE TITLE
TypeError: "C.collection(...).where(...).doc is not a function"

### ISSUE THREAD

**Issue by gap-on** [LoveMeWithoutAll/vue-blog#8]
https://github.com/LoveMeWithoutAll/vue-blog/blob/f11a4ad783658e8c19910308e864b2cf9f545026/src/components/PostViewer.vue#L91

vue-blog/src/components/PostViewer.vue 
TypeError: "C.collection(...).where(...).doc is not a function"

if you go to the direct link to the blog page or update it

**Comment by LoveMeWithoutAll** [comment]
Thank you for issue. I'll check it

**Comment by LoveMeWithoutAll** [comment]
The problem has been solved.
Thank you for your issue.
